### ISSUE TITLE
Type error in audio check.

### ISSUE THREAD

**Issue by dmtrmary** [omegalabsinc/omegalabs-bittensor-subnet#80]
https://github.com/omegalabsinc/omegalabs-bittensor-subnet/blob/63cc4a49fcf1949e52df9ad5f9e5e63da8fc6ed4/neurons/validator.py#L568

There is error in this line.
`audio_bytes_from_youtube` is string but `submitted_audio_bytes` is bytes. So they can't be matched.

This line should be fixed like this.
audio_bytes_from_youtube = base64.b64encode(audio_bytes_from_youtube)

**Comment by salmanshah1d** [comment]
https://github.com/omegalabsinc/omegalabs-bittensor-subnet/commit/2f80413f2124012624b9fe83dd1a9c47d345e35a

**Comment by dhl1402** [comment]
But miners are decoding bytes to string here: https://github.com/omegalabsinc/omegalabs-bittensor-subnet/blob/main/omega/miner_utils.py#L151

So I think miners are subbmiting string to valis. Am I missing something?

**Comment by dmtrmary** [comment]
https://github.com/omegalabsinc/omegalabs-bittensor-subnet/blob/2f80413f2124012624b9fe83dd1a9c47d345e35a/omega/protocol.py#L96

I think it's converted to bytes again because of this.
